project_name: envreplace
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - mips
      - mips64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X "main.appName={{ .ProjectName }}"
      - -X "main.appVersion={{ .Tag }} "
      - -X "main.appCommit={{ .FullCommit }}"
      - -X "main.appBranch={{ .Branch }}"
      - -X "main.appBuild={{ .Date }}"
      - -X "main.goVersion={{ .Env.GOVERSION }}"
dockers:
  - image_templates:
      - "ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/fkmeland/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/fkmeland/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - "ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    use: buildx
    goos: linux
    goarch: arm64
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/fkmeland/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/fkmeland/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - "ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-mips"
    use: buildx
    goos: linux
    goarch: mips
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/mips"
      - "--label=org.opencontainers.image.created={{.Date}}-mips"
      - "--label=org.opencontainers.image.title={{.ProjectName}}-mips"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}-mips"
      - "--label=org.opencontainers.image.version={{.Version}}-mips"
  - image_templates:
      - "ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-mips64"
    use: buildx
    goos: linux
    goarch: mips64
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/mips64"
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/fkmeland/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/fkmeland/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-mips
      - ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-mips64
  - name_template: ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}
    image_templates:
      - ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}-amd64
      - ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}-arm64v8
      - ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}-mips
      - ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}-mips64
  - name_template: ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64v8
      - ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-mips
      - ghcr.io/fkmeland/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-mips64
  - name_template: ghcr.io/fkmeland/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-mips
      - ghcr.io/fkmeland/{{ .ProjectName }}:{{ .Version }}-mips64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
